# Generated by Django 3.2.14 on 2023-08-26 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0005_auto_20230826_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhibit',
            name='user',
        ),
        migrations.RemoveField(
            model_name='inspiration',
            name='followed',
        ),
        migrations.RemoveField(
            model_name='inspiration',
            name='follower',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='user',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='Exhibit',
        ),
        migrations.DeleteModel(
            name='Inspiration',
        ),
        migrations.DeleteModel(
            name='Upload',
        ),
    ]
