# Generated by Django 3.2.14 on 2023-08-26 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0007_customuser_exhibit_inspiration_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspiration',
            name='followed',
        ),
        migrations.RemoveField(
            model_name='inspiration',
            name='follower',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='user',
        ),
        migrations.DeleteModel(
            name='Exhibit',
        ),
        migrations.DeleteModel(
            name='Inspiration',
        ),
        migrations.DeleteModel(
            name='Upload',
        ),
    ]
