# Generated by Django 3.2.14 on 2023-08-27 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_network_api', '0002_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='file',
            new_name='image_or_fbx',
        ),
    ]
