# Generated by Django 3.2.14 on 2023-08-27 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_network_api', '0004_auto_20230828_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_or_fbx',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=510),
        ),
    ]
